#!/bin/bash

# bbridge install
echo '---bbridge install'
git clone git@github.com:s-a-y/bbridge.git
cd bbridge
npm i

# stellar-rest install
echo '---stellar-rest install'
git clone https://github.com/umbrellab/stellar-rest.git
cd stellar-rest
sudo npm i
cp config-example.json config.json


# stellar-monitor install
echo '---stellar-monitor install'
git clone git@github.com:s-a-y/stellar-monitor.git
cd stellar-monitor
sudo npm i


# gatewayd install
echo '---gatewayd install'
git clone https://github.com/umbrellab/gatewayd.git
cd gatewayd
sudo apt-get -y install git python-software-properties python g++ make libpq-dev
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get -y update
sudo apt-get -y install nodejs postgresql postgresql-client
sudo npm install --global pg grunt grunt-cli forever db-migrate jshint
sudo npm install pm2 -g --unsafe-perm
npm install --save
sudo psql -U postgres -c "create user gatewayd_user with password 'password'"
sudo psql -U postgres -c "create database gatewayd_db with owner gatewayd_user encoding='utf8'"
sudo psql -U postgres -c "create database gatewayd_db_test with owner gatewayd_user encoding='utf8'" 
cp ../bbridge/Gatewaydfile.js .
   

