#!/bin/bash

#local run
if (gnome-terminal -h); then 
  gnome-terminal \
	--tab --title="gateway" -e "bash -c \"gatewayd/bin/gateway start;
	if !( pm2 desc 4 ); then
	    gatewayd/bin/gateway start
	fi;exec bash\"" \
	--tab --title="stellar" -e "bash -c \"sleep 2; node stellar-rest/server.js;exec bash\"" \
	--tab --title="bbridge" -e "bash -c \"sleep 3; node bbridge/bin/www;exec bash\"" 

fi;


#server run
if !(screen -v); then 
	pm2 kill
	killall node
	screen -dmS stellar node stellar-rest/server.js
	screen -dmS bbridge node bbridge/bin/www
	screen -dmS gatewayd gatewayd/bin/gateway start
	if !( pm2 desc 4 ); then
	    screen -dmS gatewayd gatewayd/bin/gateway start
	    pm2 list
	fi
	screen -ls
fi;

#WID=$(xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)"| awk '{print $5}')

#xdotool windowfocus $WID


#xdotool set_window $WID
#wmctrl -i -a $WID


