#!/bin/bash

# bbridge install
echo '---bbridge install'
git clone git@github.com:s-a-y/bbridge.git
cd bbridge
sudo npm i
cd ..

# stellar-rest install
echo '---stellar-rest install'
git clone https://github.com/umbrellab/stellar-rest.git
cd stellar-rest
sudo npm i
cp config-example.json config.json
cd ..


# stellar-monitor install
echo '---stellar-monitor install'
git clone git@github.com:s-a-y/stellar-monitor.git
cd stellar-monitor
sudo npm i
cd ..


# gatewayd install
echo '---gatewayd install'
git clone https://github.com/umbrellab/gatewayd.git
cd gatewayd
sudo apt-get -y install git python-software-properties python g++ make libpq-dev
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get -y update
sudo apt-get -y install nodejs postgresql postgresql-client
sudo npm install --global pg grunt grunt-cli forever db-migrate jshint
sudo npm install pm2 -g --unsafe-perm
sudo npm install --save
cp ../bbridge/Gatewaydfile.js .
   
